//{{NO_DEPENDENCIES}}
// Archivo de inclusión generado de Microsoft Visual C++.
// Usado por Comercios.rc
//
#define ID_MainWnd                      9
#define ID_WINInSes                     101
#define ID_RegAdWnd                     104
#define IDR_MENU1                       108
#define IDR_MENU2                       111
#define ID_InfoUs                       112
#define IDR_MENU3                       112
#define ID_RegUsWnd                     113
#define ID_ListUsersWnd                 114
#define ID_RestPassWnd                  116
#define ID_RegCliWnd                    117
#define ID_ListClientsWnd               118
#define ID_ContSes                      1001
#define ID_EDUser                       1002
#define ID_EDPassword                   1003
#define ID_EDPassword2                  1004
#define ID_EDCom                        1005
#define ID_Registrar                    1006
#define ID_EDCliTelef                   1006
#define ID_Salir                        1007
#define ID_RegAdmin                     1010
#define ID_Regresar                     1011
#define ID_LoadPFP                      1013
#define IDC_SYSLINK1                    1021
#define ID_NumCli                       1036
#define ID_UpUs                         1041
#define ID_NumActProm                   1042
#define ID_UsName                       1043
#define ID_EDUsNombre                   1044
#define ID_NumNoActProm                 1045
#define ID_NumTotCon                    1046
#define ID_NumMonCon                    1047
#define ID_Guardar                      1047
#define ID_EDUsAlias                    1048
#define ID_RegUser                      1050
#define ID_AdCheck                      1051
#define ID_ListaUsuarios                1053
#define ID_ActUs                        1058
#define ID_ListaInfoUs                  1060
#define ID_Eliminar                     1061
#define ID_NewPass                      1063
#define ID_ListUs                       1068
#define ID_EDPassRest                   1069
#define ID_EDConfRest                   1070
#define ID_FechaCli                     1073
#define ID_EDCliNombre                  1074
#define ID_EDCliAlias                   1075
#define ID_EDCliMail                    1076
#define ID_ActCli                       1077
#define ID_ActCliWnd                    1077
#define ID_ListaClientes                1078
#define ID_RegProWnd                    1078
#define ID_ListaInfoCli                 1079
#define ID_ListPromotionsWnd            1079
#define ID_ActProWnd                    1080
#define ID_FechaRegCli                  1081
#define ID_RegConWnd                    1081
#define ID_ActivePro                    1082
#define ID_ListTicketsWnd               1082
#define ID_FechaPro                     1083
#define ID_DeleteUserWnd                1083
#define ID_EDProNombre                  1084
#define ID_DeletePromotionWnd           1084
#define ID_EDProMonto                   1085
#define ID_DeleteClientWnd              1085
#define ID_EDProPrj                     1086
#define ID_ActPro                       1087
#define ID_FechaRegPro                  1088
#define ID_ListaInfoPro                 1089
#define ID_ListaPromociones             1090
#define ID_FechaCon                     1091
#define ID_EDConMonto                   1092
#define ID_EDConSub                     1093
#define ID_EDConDesc                    1094
#define ID_EDConTotal                   1095
#define ID_ListaConCli                  1096
#define ID_ListaConsumos                1097
#define ID_ListaInfoCon                 1098
#define ID_FechaRegCon                  1099
#define ID_ActCon                       1100
#define ID_ListaBorrarUs                1101
#define ID_ListaBorrarPro               1102
#define ID_FechaDelPro                  1103
#define ID_ListaBorrarCli               1104
#define ID_FechaDelCli                  1105
#define ID_ListComercios                1106
#define ID_ARCHIVO_ABRIR                40001
#define ID_ARCHIVO_GUARDAR              40002
#define ID_ARCHIVO_GUARDARCOMO          40003
#define ID_ABRIR_ABRIR                  40004
#define ID_GUARDAR_GUARDAR              40005
#define ID_ABRIR_CARGARCLIENTES         40006
#define ID_ABRIR_CARGARPROMOCIONES      40007
#define ID_AYUDA_USUARIOS               40008
#define ID_AYUDA_CLIENTES               40009
#define ID_AYUDA_PROMOCIONES            40010
#define ID_AYUDA_CONSUMOS               40011
#define ID_CERRAR                       40012
#define ID_USUARIOS_NUEVOUSUARIO        40013
#define ID_USUARIOS_LISTARUSUARIOS      40014
#define ID_USUARIOS_RESTABLECERCONTRASE40015 40015
#define ID_CLIENTES_NUEVOCLIENTE        40016
#define ID_CLIENTES_LISTARCLIENTES      40017
#define ID_CERRAR_CERRARSINGUARDAR      40018
#define ID_CERRAR_CERRARYGUARDAR        40019
#define ID_GUARDAR_GUARDARCOMO          40020
#define ID_PROMOCIONES_NUEVAPROMOCION   40021
#define ID_PROMOCIONES_LISTARPROMOCIONES 40022
#define ID_CONSUMOS_NUEVOCONSUMO        40023
#define ID_CONSUMOS_LISTARCONSUMOS      40024
#define ID_CERRAR_CERRARSESI40025       40025
#define ID_ABRIR_ABRIRPROMOCIONES       40026
#define ID_ABRIR_ABRIRCONSUMOS          40027
#define ID_ABRIR_ABRIRCONSUMOS40028     40028
#define ID_ABRIR_ABRIRUSUARIOS          40029
#define ID_ABRIR_ABRIRCLIENTES          40030
#define ID_ARCHIVO_GUARDARCOMO40031     40031
#define ID_ARCHIVO_ABRIRARCHIVO         40032

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        120
#define _APS_NEXT_COMMAND_VALUE         40033
#define _APS_NEXT_CONTROL_VALUE         1107
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
